version: '3.3'
services:
  outfitr-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    ports:
      - "8080:11000"
    environment:
      - OMW_API_KEY=${OMW_API_KEY}
